In [1]:
import torch


## 数据部分基础

In [2]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel()

12

In [5]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [6]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [7]:
X=torch.arange(12,dtype=torch.float32).reshape((3,4))
Y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [8]:
#通过逻辑运算符构建二元张量
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [9]:
#对张量中所有元素进行求和
X.sum()

tensor(66.)

In [10]:
#广播机制
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [12]:
X[-1]#选择最后一个元素

tensor([ 8.,  9., 10., 11.])

In [13]:
X[1:3]#拿出第一行和第二行

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
#将元素写入矩阵
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
#为多个元素赋相同的值
X[0:2,:]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [16]:
# 运行一些操作可能会导致为新结果分配内存
before=id(Y)
Y=Y+X
id(Y)==before

False

In [17]:
##执行原地操作
Z=torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:]=X+Y
print('id(Z):',id(Z))

id(Z): 4587412672
id(Z): 4587412672


In [18]:
# 原地操作
before=id(Y)
Y+=X
id(Y)==before

True

In [19]:
#转换为Numpy张量
A=X.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [20]:
#将大小为1的张量转换为Python表量
a=torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [21]:
#处理缺失的数据
# 运行一些操作可能会导致为新结果分配内存
before=id(Y)
Y=Y+X
id(Y)==before

False

In [22]:
a = torch.arange(12)
b= a.reshape((3,4))
b[:]=2
a
b

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2],
        [2, 2, 2, 2]])

## 线性代数

标量由只有一个元素的张量表示

In [23]:
import torch

x=torch.tensor([3.0])
y=torch.tensor([2.0])

x+y,x*y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

可以将向量视为标量值组成的列表

In [25]:
x=torch.arange(4)
x

tensor([0, 1, 2, 3])

通过张量的索引来访问任一元素

In [26]:
x[3]

tensor(3)

In [27]:
x.shape

torch.Size([4])

通过指定两个分量m和n来创建一个形状为m*n的矩阵

In [28]:
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

矩阵的转置

In [29]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [33]:
B=torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
B


tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [35]:
#B为对称矩阵
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

我们可以构建具有更多轴的数据结构

In [37]:
X=torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

给具有相同形状的任何两个张量，任何按元素二元运算的结果都将是相同形状的张量

In [39]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone() #通过分配新内存，将A的一个副本分配给B
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵将按元素乘法称为*哈达玛积（Hadamard Product）*

In [41]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [42]:
a=2
X=torch.arange(24).reshape(2,3,4)
a+X,(a*X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 torch.Size([2, 3, 4]))

计算其元素的和

In [43]:
x=torch.arange(4,dtype=torch.float32)
x,x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [52]:
A=torch.arange(2*20,dtype=torch.float32).reshape(2,5,4)
A.sum(axis=0).shape
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

一个与求和相关的量是平均值（mean或者average）

In [49]:
A.mean(),A.sum()/A.numel()

(tensor(19.5000), tensor(19.5000))

In [53]:
A.sum(axis=0)

tensor([[20., 22., 24., 26.],
        [28., 30., 32., 34.],
        [36., 38., 40., 42.],
        [44., 46., 48., 50.],
        [52., 54., 56., 58.]])

In [58]:
sum_A=A.sum(axis=0,keepdims=True)
sum_A

tensor([[[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

通过广播机制将A处以sum_A

In [57]:
A/sum_A

tensor([[[0.0000, 0.0455, 0.0833, 0.1154],
         [0.1429, 0.1667, 0.1875, 0.2059],
         [0.2222, 0.2368, 0.2500, 0.2619],
         [0.2727, 0.2826, 0.2917, 0.3000],
         [0.3077, 0.3148, 0.3214, 0.3276]],

        [[1.0000, 0.9545, 0.9167, 0.8846],
         [0.8571, 0.8333, 0.8125, 0.7941],
         [0.7778, 0.7632, 0.7500, 0.7381],
         [0.7273, 0.7174, 0.7083, 0.7000],
         [0.6923, 0.6852, 0.6786, 0.6724]]])

某个轴计算A元素的累积求和

In [63]:
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]])

In [67]:
A.cumsum(axis=0)

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]]])

In [68]:
A.cumsum(axis=1)

tensor([[[  0.,   1.,   2.,   3.],
         [  4.,   6.,   8.,  10.],
         [ 12.,  15.,  18.,  21.],
         [ 24.,  28.,  32.,  36.],
         [ 40.,  45.,  50.,  55.]],

        [[ 20.,  21.,  22.,  23.],
         [ 44.,  46.,  48.,  50.],
         [ 72.,  75.,  78.,  81.],
         [104., 108., 112., 116.],
         [140., 145., 150., 155.]]])

In [69]:
A.cumsum(axis=2)

tensor([[[  0.,   1.,   3.,   6.],
         [  4.,   9.,  15.,  22.],
         [  8.,  17.,  27.,  38.],
         [ 12.,  25.,  39.,  54.],
         [ 16.,  33.,  51.,  70.]],

        [[ 20.,  41.,  63.,  86.],
         [ 24.,  49.,  75., 102.],
         [ 28.,  57.,  87., 118.],
         [ 32.,  65.,  99., 134.],
         [ 36.,  73., 111., 150.]]])

In [92]:
A.sum(axis=2)

tensor([[  6.,  22.,  38.,  54.,  70.],
        [ 86., 102., 118., 134., 150.]])

In [70]:
A.cumsum(axis=-1)

tensor([[[  0.,   1.,   3.,   6.],
         [  4.,   9.,  15.,  22.],
         [  8.,  17.,  27.,  38.],
         [ 12.,  25.,  39.,  54.],
         [ 16.,  33.,  51.,  70.]],

        [[ 20.,  41.,  63.,  86.],
         [ 24.,  49.,  75., 102.],
         [ 28.,  57.,  87., 118.],
         [ 32.,  65.,  99., 134.],
         [ 36.,  73., 111., 150.]]])

点积是相同位置的按元素乘积的和

In [73]:
x=torch.arange(4,dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

我们可以通过执行按元素乘法，进行求和，然后来表示两个向量的点积

In [74]:
torch.sum(x*y)

tensor(6.)

##### Q:m*n的矩阵
##### x:n*1的列向量
##### 得m*1的列向量

In [82]:
Q=torch.arange(20,dtype=torch.float32).reshape(5,4)

In [83]:
Q.shape,x.shape

(torch.Size([5, 4]), torch.Size([4]))

In [84]:
Q,x

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]))

In [85]:
torch.mv(Q,x)

tensor([ 14.,  38.,  62.,  86., 110.])

##### Q:5*4的矩阵
##### W:4*3的矩阵
##### 得5*3的列向量

In [86]:
W=torch.ones(4,3)
torch.mm(Q,W)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

L2范数是向量元素平方和的平方根
$$
\|\mathbf{x}\|_2=\sqrt{\sum_{i=1}^n x_i^2}
$$

In [89]:
u=torch.tensor([3.0,-4.0])
torch.norm(u)

tensor(5.)

L1范数是向量元素绝对值之和
$$
\|\mathbf{x}\|_1=\sum_{i=1}^n\left|x_i\right|
$$

In [90]:
torch.abs(u).sum()

tensor(7.)

F范数(Frobenius nrom):矩阵元素的平方和的平方根
$$
\|\mathbf{X}\|_F=\sqrt{\sum_{i=1}^m \sum_{j=1}^n x_{i j}^2}
$$

In [91]:
torch.norm(torch.ones((4,9)))

tensor(6.)